.TH jumpnbump 6 "August 25th, 2002"
.SH NAME
jumpnbump \- Cute multiplayer platform game with bunnies
.SH SYNOPSIS
jumpnbump \fR[\fB-dat \fIlevelname\fR] [\fB-port \fIport \fB-net \fIplayer hostname rport\fR] [\fB-fireworks\fR] [\fB-fullscreen\fR] [\fB-nosound\fR] [\fB-musicnosound\fR] [\fB-nogore\fR] [\fB-noflies\fR] [\fB-mirror\fR] [\fB-scaleup\fR] [\fB-v\fR] [\fB-h\fR]
.SH DESCRIPTION
You, as a bunny, have to jump on your opponents to make them
explode. It's a true multiplayer game, you can't play this alone.
It has network support.
.SH OPTIONS
.IP "-dat \fIlevelname\fR"
Load \fIlevelname\fR and use it as the level for this game.
.IP "-port \fIport\fR"
Use \fIport\fR as the port to listen on for a network game. Use this
with -net.
.IP "-net \fIplayer hostname rport"
Connect (using a network) to another person running jump'n'bump on
\fIhostname\fR, and listening on \fIrport\fR. You will be player
number \fIplayer\fR.
.IP "-fireworks"
Run the program in "screensaver" mode. This is useful with -fullscreen.
.IP "-fullscreen"
Run jump'n'bump in fullscreen mode.
.IP "-nosound"
Run jump'n'bump without sound.
.IP "-musicnosound"
Run jump'n'bump with music but no sound effects.
.IP "-nogore"
Play without blood, familymode.
.IP "-noflies"
Disable flies.
.IP "-mirror"
Play with mirrored level.
.IP "-scaleup"
Play with doublesize resolution (800x512).
.IP "-h"
Print help.
.IP "-v"
Print version, compile time and if network code is compiled in.
.SH USAGE
The goal of the game is to jump on the other players. Each rabbit has
three control keys.
.IP "Player 1 (Dott)"
Left - Left
.br
Right - Right
.br
Jump - Up
.IP "Player 2 (Jiffy)"
Left - A
.br
Right - D
.br
Jump - W
.IP "Player 3 (Fizz)"
Left - J
.br
Right - L
.br
Jump - I
.IP "Player 4 (Mijji)"
Left - 4
.br
Right - 5
.br
Jump - 8
.IP "In the game"
Turn on/off computer play (AI) of bunny 1 - 1
.br
Turn on/off computer play (AI) of bunny 2 - 2
.br
Turn on/off computer play (AI) of bunny 3 - 3
.br
Turn on/off computer play (AI) of bunny 4 - 4
.br
.SH SECRET CODES
You can type these while in the game
.br
jetpack - you can fly
.br
pogostick - the bunnies keep jumping
.br
bunniesinspace - gravity is lower, you can jump higher
.br
lordoftheflies - the flies are attracted
.br
bloodisthickerthanwater - water turns to blood
.SH LEVELS
There are two programs to help you make your own levels: jnbpack and jnbunpack.
.PP
jnbpack -o /tmp/newlevel.dat <file1> <file2> <file3> etc
.PP
or you can just put all the files in a dir, cd to that dir and do
.PP
jnbpack -o /tmp/newlevel.dat *
.PP
and it will put all the files in the current dir inside the packfile.
Don't try things like jnbpack -o stuff.dat ../file.c because it will add
"../file.c" as the filename in the packfile, which won't work.
.PP
jnbunpack level.dat
.br
will unpack it in the current directory.
.PP
With gobpack you can convert .gob files (which are sprites, described in
gob.txt) into .pcx files which you can edit with gimp for example, then
convert back to a .gob and use it in your own level.
.PP
gobpack -u font menu.pcx
.PP
will unpack font.gob using the color palette from menu.pcx and write the
files font.pcx font.txt. The other gob files should use level.pcx for the
correct palette.
.PP
gobpack font
.PP
will generate font.gob from font.pcx and the specifications in font.txt.
The .pcx files should be resaved with another program, as they are not
packed and are thus very large.
.SH AUTHORS
.PP
Chuck Mason <cemason@users.sourceforge.net>, Jon Atkins <jcatki@home.com>,
Philippe Brochard <phil.brochard@wanadoo.fr>, Gürkan Sengün <gurkan@linuks.mine.nu>,
Florian Schulze <crow@icculus.org>, Ricardo Cruz <rick2@aeiou.pt> and "timecop" <timecop@japan.co.jp> are
the authors of jump'n'bump.
.PP
This program is a UNIX port of the old DOS game by brainchilddesign. 
.PP
This manual page was written for the Debian GNU/Linux distribution because
the original program does not have a manual page.
.PP
This manual page was written by Joe Wreschnig <piman@sacredchao.net>, for the
Debian GNU/Linux system (but may be used by others). The manual page is kept
up to date by Gürkan Sengün <gurkan@linuks.mine.nu>.
